apiVersion: apps/v1
kind: Deployment
metadata:
  name: tekton-events-controller
spec:
  template:
    spec:
      imagePullSecrets:
        helmTemplateRemoveMe: |
          {{- with .Values.eventscontroller.imagePullSecrets }}
            {{- toYaml . | nindent 6 }}
          {{- end }}
      containers:
      - name: tekton-events-controller
      helmTemplateRemoveMe: |
        image: {{ .Values.eventscontroller.deployment.image }}
